info:
  model: int-scaffold
packages:
- gitBranch: main
  gitServerName: rahulsiv
  gitUrl: https://github.com/Rahul-Sivakumar-IBM
  gitUsername: Rahul-Sivakumar-IBM
  name: PackageProject
version: '1.0'
